"""add deleted column

Revision ID: b84a7349f630
Revises: b2cfe2e0231e
Create Date: 2020-10-25 18:57:24.698733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84a7349f630'
down_revision = 'b2cfe2e0231e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted')
    # ### end Alembic commands ###
