"""add sale column

Revision ID: c4a42f847203
Revises: b84a7349f630
Create Date: 2020-10-25 19:04:21.598599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a42f847203'
down_revision = 'b84a7349f630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_sale', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_sale')
    # ### end Alembic commands ###
