# Generated by Django 3.1.3 on 2020-11-15 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0005_card_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods'),
        ),
        migrations.AddField(
            model_name='card',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
