# Generated by Django 3.1.3 on 2020-11-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0006_auto_20201115_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=64),
        ),
    ]
