version: '3.5'

services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: toys
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .\\data\\pgdata:/var/lib/postgresql/data/pgdata